### PR TITLE
Build Step which do not sync with Template Job

### LINKED ISSUE #52: Support for additional Build Steps in Implementation Job
Hi,

I want to configure my jobs in such a way that I can add some additional(extra build steps which is not  there in template job) build or post build step in my implementation job but when I save the job, all additional step got overridden by template job. And there are only steps which are present in template job 

I want to configure my  job as follows :

In Template Project there are:
 
- Some Build Steps
- Some Post Build Steps

And In Implementation Job I want

- All the Build Steps and Post Build Steps of template job
- additionally I want some more Build step and post build steps

Can you please suggest. How can I do this.

### PR DESCRIPTION
**Pull request by arpitgold**
"This commit fixes #52 "

### CODE REVIEW

**Comment by arpitgold** [comment]
Hi @JoelJ ,

Can you please review this code.

**Comment by arpitgold** [comment]
Any update on this ??

**Comment by drekbour** [comment]
I see your intent here (+100 for drawing a picture) and it falls into the same category as PR #37. It comes from a desire for "real" templates in Jenkins but ends up adding a lot of complexity to the project to achieve only part of that goal.

Although not as generically powerful, I have a [Conditional build step](https://wiki.jenkins-ci.org/display/JENKINS/Conditional+BuildStep+Plugin) based on a job parameter which can be used to enable it only on certain jobs. That requires zero additional coding.

I'm going to add a page on design rationale and thoughts for the current ez-templates and any future template plugin which realistically could generalise templating.

**Comment by arpitgold** [comment]
I sees problems in Conditional build Step plugin 
If my all jobs have same build workflow, but my job categories are far different;
so 1 job will show jobs which are not relevant with the other.
Example : 
Fruits and Vehicle and many more are having same workFlow (ez-Template master job)
and apple, banana, peer belongs to 1 group (child jobs which derives master job)
but car, bus, bike belongs to another group.

So I have to either create same workflow for all category, so If I have 25 category I have to replicate it 25 times which defeat templatization.

Or I can use conditional plugin, but it will display jobs as
Choose jobs to built for Fruit 
  - Apple
  - Banana
  - Peer
  - Car
  - Bus
etc.
So I created this type of extension in code, which has a new type of build section which act as place holder and can contain many step but will not sync with master job. It will provide too much flexibility.

We can document it and provide it as real templating feature.
Your thoughts ?

**Comment by drekbour** [comment]
1. "ez-Template master job" has a job parameter $CATEGORY and some Conditional build steps (see also Flexible publish plugin!) based on this type being "FRUIT" or "VEHICLE".
2. Jobs like Apple and Banana set $CATEGORY = FRUIT and jobs like Car set it to VEHICLE

The only downside (and it *is* quite major) is that the single master job must contain all (conditional) build steps which is seriously ugly if you have more than a few things like this. If you have huge divergence then I question the value of applying a single template to them all.

ez-templates 2 (which is just an idea right now - no code has been written) is going to have a generic way for (advanced users) to retain arbitrary xpath when syncing impls with their template. Once that is in place it becomes reasonably trivial to have the idea of an "abstract" template with a placeholder build step.

However it will make a huge mess if applied in the existing 1.x code, you've cloned many piece of another plugin and between this and the other tickets raised - I'm not sure what your master solution is at all.

My take on your diagram:
* Ez-1 use conditions above.
* Ez-2 would allow a placeholder build step to be implemented by all children
* Some other plugin is responsible for implementing a compound build step which could be used as the implementation of the placeholder

**Comment by emoshaya** [comment]
Unfortunately, this change was required for the plugin to work with https://wiki.jenkins-ci.org/display/JENKINS/Multijob+Plugin

Looks like the dependency was removed because this change never got merged.

https://github.com/jenkinsci/tikal-multijob-plugin/commit/ae30e9b5b5f80854d252f563603131153e3955cb

We use the Multijob plugin extensively but unfortunately can't template this job type without being able to exclude the multijob phases...

**Comment by drekbour** [comment]
This github project is defunct, please vote/comment on https://issues.jenkins-ci.org/browse/JENKINS-37972 and we can attempt to re-implement template build steps in more future-friendly manner.
I don't use multijob myself so look forward to seeing how it works

**Pull request closed without merging**
