### PR TITLE
fix issue #31: support for Promoted Builds plugin

### PR DESCRIPTION
**Pull request by juanpablo-santos**
PR for issue #31, based on code noted at https://github.com/JoelJ/ez-templates/issues/31#issuecomment-99121574.

### CODE REVIEW

**Comment by drekbour** [comment]
Thanks for the submission. There are a few things needs tidying here:
1 This introduces a hard dependency on another plugin. The Maven dependency should be optional. All usage of code from Promoted builds should be contained in a class that is only accessed if that plugin appears to be installed.
2 There are lots of formatting changes applied by an IDE. That kind of thing shouldn't be included in a feature branch as it pollutes the meaningful change and (as here) leads to merge conflicts where none really exists.
3 I think some comments might help explain why the code does what it does as it's pretty opaque to me.

**Comment by juanpablo-santos** [comment]
Hi,

tidied up the PR as per your comments, hope it is fine now for inclusion.

br,
juan pablo

**Comment by drekbour** [comment]
Much better. I think point 2 still applies. I will do a manual merge and tinker with the history a bit to delete all the "final"s that have appeared all over the code. When merged you will need to delete your feature branch as the commit history will be different to same code in master.

**Comment by juanpablo-santos** [comment]
Hi,

apologies on the formatting changes, thought this morning I had get rid of them, but seems I reintroduced them when including the PromotedBuildsTemplateUtils class. Urg. Will delete the feature branch when merged.

Thanks!

**Comment by drekbour** [comment]
Integrated without an explicit merge from this PR.

**Pull request closed without merging**
